filter:
    excluded_paths: ['vendor/*', 'tests/*']
    paths: ['src/*']

checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_pdepend: true
    php_sim: true
    sensiolabs_security_checker: true

build:
    dependencies:
        before:
            - "sudo composer self-update"
        override:
            - "composer install --no-dev --no-interaction --prefer-dist"
    environment:
        php: '5.5.25'
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
    tests:
        override:
            -
                command: 'phpunit -c tests/ --colors --coverage-clover=clover.xml tests/unit'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
