language: php

php:
    - 5.5
    - 5.6

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/phpunit -c tests/ --colors --coverage-clover=build/logs/clover.xml tests/unit
